apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssp-resource-poc
  name: ssp-resource-poc
  namespace: $(kubernetes-namespace)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssp-resource-poc
  template:
    metadata:
      labels:
        app: ssp-resource-poc
    spec:
      containers:
      - image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/ssp-resource-poc:$(Build.BuildId)
        imagePullPolicy: Always
        name: ssp-resource-poc